export const ErrorCodes = {
  // Tool errors (TOOL_xxx)
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  TOOL_TIMEOUT: 'TOOL_TIMEOUT',
  TOOL_PERMISSION_DENIED: 'TOOL_PERMISSION_DENIED',

  // LLM errors (LLM_xxx)
  LLM_API_ERROR: 'LLM_API_ERROR',
  LLM_RATE_LIMITED: 'LLM_RATE_LIMITED',
  LLM_CONTEXT_TOO_LONG: 'LLM_CONTEXT_TOO_LONG',
  LLM_INVALID_RESPONSE: 'LLM_INVALID_RESPONSE',

  // Config errors (CONFIG_xxx)
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_PERMISSION_DENIED: 'CONFIG_PERMISSION_DENIED',

  // Connector errors (CONNECTOR_xxx)
  CONNECTOR_NOT_FOUND: 'CONNECTOR_NOT_FOUND',
  CONNECTOR_AUTH_FAILED: 'CONNECTOR_AUTH_FAILED',
  CONNECTOR_EXECUTION_FAILED: 'CONNECTOR_EXECUTION_FAILED',

  // Validation errors (VALIDATION_xxx)
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',

  // Hook errors (HOOK_xxx)
  HOOK_EXECUTION_FAILED: 'HOOK_EXECUTION_FAILED',

  // Generic
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
